#!/bin/bash
set -e

echo "[TFTP] Starting dnsmasq TFTP server..."

# Get boot server IP from environment or default to api (Docker hostname)
BOOT_SERVER_IP="${BOOT_SERVER_IP:-api}"
echo "[TFTP] Boot server IP: $BOOT_SERVER_IP"

# Create TFTP directories
mkdir -p /data/tftp

# Download iPXE boot files if they don't exist
echo "[TFTP] Checking iPXE boot files..."

if [ ! -f /data/tftp/undionly.kpxe ]; then
    echo "[TFTP] Downloading undionly.kpxe..."
    curl -L -o /data/tftp/undionly.kpxe \
        https://boot.ipxe.org/undionly.kpxe 2>&1 || echo "[TFTP] Warning: Failed to download undionly.kpxe"
    if [ -f /data/tftp/undionly.kpxe ]; then
        echo "[TFTP] ✓ undionly.kpxe downloaded successfully"
    fi
fi

if [ ! -f /data/tftp/ipxe.efi ]; then
    echo "[TFTP] Downloading ipxe.efi (UEFI)..."
    curl -L -o /data/tftp/ipxe.efi \
        https://boot.ipxe.org/ipxe.efi 2>&1 || echo "[TFTP] Warning: Failed to download ipxe.efi"
    if [ -f /data/tftp/ipxe.efi ]; then
        echo "[TFTP] ✓ ipxe.efi downloaded successfully"
    fi
fi

# Create boot.ipxe menu
echo "[TFTP] Generating boot menu script with available OS installers..."

cat > /data/tftp/boot.ipxe << 'EOF'
#!ipxe
# Netboot Orchestrator iPXE Menu
# This script is generated by TFTP server startup

set color_header 0x0000ff
set color_item 0x00ffff
set color_selected 0xffffff

:menu
clear
cpuid --ext -- x86_64 && set FIRMWARE efi || set FIRMWARE bios
echo
echo ====================================
echo  🚀 Netboot Orchestrator
echo ====================================
echo
echo  Firmware: ${FIRMWARE}
echo  MAC Address: ${net0/mac}
echo  IP Address: ${net0/ip}
echo  Boot Server: ${next-server}
echo
echo  Available Options:
echo
echo  1) Boot from HTTP server
echo  2) Boot from iSCSI target
echo  3) Chain to iPXE menu API
echo  4) iPXE command shell
echo  9) Exit
echo
choose --timeout 15 --default 3 selected || goto exit

:1
echo
echo Attempting to boot from HTTP server...
sleep 2
chain http://${next-server}:8000/api/v1/boot/ipxe/menu || goto menu

:2
echo
echo Attempting to boot from iSCSI...
sleep 2
set root-path iscsi:${next-server}::3260:0:*:*
sanboot ${root-path} || goto menu

:3
echo
echo Fetching menu from Netboot Orchestrator API...
sleep 2
chain http://${next-server}:8000/api/v1/boot/ipxe/menu || goto menu

:4
shell
goto menu

:exit
echo
echo Exiting iPXE...
sleep 1
EOF

echo "[TFTP] Boot menu created!"
echo "[TFTP] TFTP root: /data/tftp"
echo "[TFTP] Available boot files:"
ls -lah /data/tftp/ 2>/dev/null | grep -E "kpxe|efi|ipxe" || echo "[TFTP] No boot files found yet"

echo "[TFTP] Starting dnsmasq..."
exec dnsmasq -C /tftp/config/dnsmasq.conf -d
